Камень судьбы
htmlacademy-yii/204543-task-force-2 pull request #2
Opened 2021-11-06 16:53 UTC by nataliasevostyanova

2021-11-07 13:37 UTC, b1rdex requested changes
Нужно доработать класс и ещё написать тест для него

2021-11-07 13:37 UTC, b1rdex commented on classes/TaskStatusAction
> +<? php
Этот файл стоит удалить

2021-11-07 13:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public function getStatuses ()
```suggestion
    /*
     * получает массив статусов задания
     */
    public function getStatuses(): array
```

2021-11-07 13:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public function getStatuses ()
Комментарий к методам нужно делать в виде phpdoc, пустая строка после комментария не нужна

2021-11-07 13:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +     public function __construct($clientId, $doerId)
Ещё нужно принимать текущий статус задания в конструктор

2021-11-07 13:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +     public function __construct($clientId, $doerId)
Рекомендую добавить типизацию везде, например тут это будет `int $clientId, int $orderId, string $status`

2021-11-07 13:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +        	break;
1. да, нужно переиспользовать константы, этот вариант лучше
2. `$actualStatus` стоит поменять на `$action`, т.к. метод принимает действие
3. `switch ($actions[]) {` – тут ошибка, нужно поменять `$actions[]` на имя параметра метода
4. `case ACTION_CREATE` – тут ошибка, обращение к константе класса должно быть `self::ACTION_CREATE`
5. `$actualStatus == self::STATUS_NEW;` тут лишнее равно. Это сравнение, а должно быть присвоение
6. `return $actualStatus; break;` 1) вместо присвоения переменной и return можно делать сразу return значения и 2) break не нужен, т.к. return и так делает выход из метода

2021-11-07 13:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    }
И ещё нужно добавить метод, который будет «Определять список доступных действий в текущем статусе»

2021-11-07 13:52 UTC, nataliasevostyanova commented
Спасибо! Исправлю

вс, 7 нояб. 2021 г., 16:38 Anatoly Pashin ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Нужно доработать класс и ещё написать тест для него
> ------------------------------
>
> In classes/TaskStatusAction
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r744258662>
> :
>
> > @@ -0,0 +1,8 @@
> +<? php
>
> Этот файл стоит удалить
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r744258817>
> :
>
> > +    // получает массив статусов задания
> +
> +    public function getStatuses ()
>
> ⬇️ Suggested change
>
> -    // получает массив статусов задания
> -
> -    public function getStatuses ()
> +    /*
> +     * получает массив статусов задания
> +     */
> +    public function getStatuses(): array
>
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r744258962>
> :
>
> > +
> +    private static $actions = [
> +                self::ACTION_CREATE = 'create',
> +                self::ACTION_CANSEL = 'cancel',
> +                self::ACTION_RESPOND  = 'respond',
> +                self::ACTION_PEFUSE = 'refuse',
> +                self::ACTION_FINISH = 'finish'
> +                ];
> +
> +    public $actualStatus = 'new';
> +
> +    // методы класса
> +
> +    //конструктор
> +
> +     public function __construct($clientId, $doerId)
>
> Ещё нужно принимать текущий статус задания в конструктор
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r744259406>
> :
>
> > +    // тут у меня нет пока понимания как правильно: в switch/case нужно обращаться к имени константы или к её значению? второй вариант закомментила ниже
> +
> +     /*
> +    public function getActualStatus($actualStatus)
> +     {
> +     	switch ($actions[]) {
> +    		case ACTION_CREATE:
> +        		$actualStatus == self::STATUS_NEW;
> +        		return $actualStatus;
> +        	break;
>
>
>    1. да, нужно переиспользовать константы, этот вариант лучше
>    2. $actualStatus стоит поменять на $action, т.к. метод принимает
>    действие
>    3. switch ($actions[]) { – тут ошибка, нужно поменять $actions[] на
>    имя параметра метода
>    4. case ACTION_CREATE – тут ошибка, обращение к константе класса
>    должно быть self::ACTION_CREATE
>    5. $actualStatus == self::STATUS_NEW; тут лишнее равно. Это сравнение,
>    а должно быть присвоение
>    6. return $actualStatus; break; 1) вместо присвоения переменной и
>    return можно делать сразу return значения и 2) break не нужен, т.к. return
>    и так делает выход из метода
>
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r744259698>
> :
>
> > +        		return $actualStatus;
> +        	break;
> +    		case self::ACTION_RESPOND:
> +        		$actualStatus == self::STATUS_INWORK;
> +        		return $actualStatus;
> +        	break;
> +        	case self::ACTION_REFUSE:
> +        		$actualStatus == self::STATUS_REFUSAL;
> +        		return $actualStatus;
> +        	break;
> +        	case self::ACTION_FINISH:
> +        		$actualStatus == self::STATUS_FINISH;
> +        		return $actualStatus;
> +        	break;
> +		}
> +    }
>
> И ещё нужно добавить метод, который будет «Определять список доступных
> действий в текущем статусе»
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r744258863>
> :
>
> > +    // получает массив статусов задания
> +
> +    public function getStatuses ()
>
> Комментарий к методам нужно делать в виде phpdoc, пустая строка после
> комментария не нужна
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r744259027>
> :
>
> > +
> +    private static $actions = [
> +                self::ACTION_CREATE = 'create',
> +                self::ACTION_CANSEL = 'cancel',
> +                self::ACTION_RESPOND  = 'respond',
> +                self::ACTION_PEFUSE = 'refuse',
> +                self::ACTION_FINISH = 'finish'
> +                ];
> +
> +    public $actualStatus = 'new';
> +
> +    // методы класса
> +
> +    //конструктор
> +
> +     public function __construct($clientId, $doerId)
>
> Рекомендую добавить типизацию везде, например тут это будет int
> $clientId, int $orderId, string $status
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#pullrequestreview-799539915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHXQGM372UL5JAN3OSWRZLTUKZ6L5ANCNFSM5HPZDESA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-10 06:37 UTC, b1rdex requested changes

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> + * @method getDoerAllowedAction(string $status)
Это всё не нужно дублировать в phpdoc класса. Если нужно для чего-то из этого написать комментарий, то его можно добавить у конкретного элемента так же через phpdoc
```suggestion
```

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +class TaskStatusAction
```suggestion
class TaskStatusAction
```
между phpdoc и элементом, к которму этот комментарий относится, не должно быть пустой строки

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public function __construct(int $clientId, int $doerId)
Нужно ещё принимать текущий статус задания в конструкторе (это я уже писал)

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    private int $doerId = 0;
Значения по умолчанию тут не нужны, т.к. оба свойства всегда задаются в конструкторе

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public string $action;
$status должен быть private и записываться из конструктора
$action вообще не нужен и не используется

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    }
Два этих метода не нужно было менять, они делали что нужно: 

«Необходимо написать класс, который будет определять список из всех доступных действий и статусов»

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +        		return $actualStatus = self::STATUS_FINISH;
Для чего `$actualStatus =` ? Это можно убрать, оставив просто возврат значения

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +     public function getClientAllowedAction(string $status) :? string
Статус не должен передаваться аргументом, он должен передаваться в конструктор

«Определять список доступных действий в текущем статусе»

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +                 return $action = self::ACTION_FINISH;
`$action = ` можно убрать, оставив просто возврат значения

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +             case(self::STATUS_UNDO && self::STATUS_REFUSAL && self::STATUS_FINISH):
Это так не работает. Если нужно сделать case из нескольких значений, то нужно перечислить несколько кейсов:
```php

switch ($status) {
	case 'test':
		// только если $status = 'test'
		break;

	case 'another':
	case 'more':
		// если $status = 'another' или $status = 'more'
		break;
}
```

2021-11-10 06:37 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public function getDoerAllowedAction(string $status) :? string
Это нужно обьединить с getClientAllowedAction, оставив один метод (да, может возвращаться несколько действий для одного статуса (массив))

2021-11-10 10:13 UTC, nataliasevostyanova commented
Спасибо за замечания, кое с чем я переусердствовала (типа, phpdoc). И метод
проверки допустимых действий переделывала, потому что тест выполнялся
некорректно. Но, похоже, метод был норм)

ср, 10 нояб. 2021 г., 09:37 Anatoly Pashin ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746276584>
> :
>
> > + * @property const CLIENT
> + * @property const DOER
> + * @property const STATUS_NEW
> + * @property const STATUS_UNDO
> + * @property const STATUS_INWORK
> + * @property const STATUS_REFUSAL
> + * @property const STATUS_FINISH
> + * @property const ACTION_CREATE
> + * @property const ACTION_CANCEL
> + * @property const ACTION_RESPOND
> + * @property const ACTION_DO
> + * @property const ACTION_REFUSE
> + * @property const ACTION_FINISH
> + * @property int $userId
> + * @property int $taskId
> + * @property string $userRole
> + * @property string $actualStatus
> + * @property array $statuses
> + * @property array $actions
> + * @property string $status
> + * @property string $action
> + * @method getStatus()
> + * @method getAction()
> + * @method getActualStatus(string $action)
> + * @method getClientAllowedAction(string $status)
> + * @method getDoerAllowedAction(string $status)
>
> Это всё не нужно дублировать в phpdoc класса. Если нужно для чего-то из
> этого написать комментарий, то его можно добавить у конкретного элемента
> так же через phpdoc
> ⬇️ Suggested change
>
> - * @property const CLIENT
> - * @property const DOER
> - * @property const STATUS_NEW
> - * @property const STATUS_UNDO
> - * @property const STATUS_INWORK
> - * @property const STATUS_REFUSAL
> - * @property const STATUS_FINISH
> - * @property const ACTION_CREATE
> - * @property const ACTION_CANCEL
> - * @property const ACTION_RESPOND
> - * @property const ACTION_DO
> - * @property const ACTION_REFUSE
> - * @property const ACTION_FINISH
> - * @property int $userId
> - * @property int $taskId
> - * @property string $userRole
> - * @property string $actualStatus
> - * @property array $statuses
> - * @property array $actions
> - * @property string $status
> - * @property string $action
> - * @method getStatus()
> - * @method getAction()
> - * @method getActualStatus(string $action)
> - * @method getClientAllowedAction(string $status)
> - * @method getDoerAllowedAction(string $status)
>
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746276825>
> :
>
> > +
> +class TaskStatusAction
>
> ⬇️ Suggested change
>
> -
> -class TaskStatusAction
> +class TaskStatusAction
>
> между phpdoc и элементом, к которму этот комментарий относится, не должно
> быть пустой строки
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746278125>
> :
>
> > +                 self::STATUS_NEW => 'new',
> +                 self::STATUS_UNDO => 'undo',
> +                 self::STATUS_WORKING => 'working',
> +                 self::STATUS_REFUSAL => 'failed',
> +                 self::STATUS_FINISH => 'finished',
> +                ];
> +
> +    private static array $actions = [
> +                self::ACTION_CREATE => 'create',
> +                self::ACTION_CANCEL =>'cancel',
> +                self::ACTION_RESPOND => 'respond',
> +                self::ACTION_REFUSE => 'refuse',
> +                self::ACTION_FINISH => 'finish',
> +                ];
> +
> +    public function __construct(int $clientId, int $doerId)
>
> Нужно ещё принимать текущий статус задания в конструкторе (это я уже писал)
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746278406>
> :
>
> > +    private int $clientId = 0;
> +    private int $doerId = 0;
>
> Значения по умолчанию тут не нужны, т.к. оба свойства всегда задаются в
> конструкторе
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746278718>
> :
>
> > +    public string $status;
> +    public string $action;
>
> $status должен быть private и записываться из конструктора
> $action вообще не нужен и не используется
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746282641>
> :
>
> > +    /**
> +     * @param array $statuses
> +     * @param
> +     * @return string $status
> +     */
> +    public function getStatus($key)
> +    {
> +        return $status = self::$statuses[$key];
> +    }
> +
> +    /**
> +     * @param array $actions
> +     * @return string $actions
> +     */
> +    public function getAction($key)
> +    {
> +        return $action = self::$actions[$key];
> +    }
>
> Два этих метода не нужно было менять, они делали что нужно:
>
> «Необходимо написать класс, который будет определять список из всех
> доступных действий и статусов»
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746283113>
> :
>
> > +        		return $actualStatus = self::STATUS_NEW;
> +        	case self::ACTION_CANCEL:
> +        		return $actualStatus = self::STATUS_UNDO;
> +        	case self::ACTION_RESPOND:
> +        		return $actualStatus = self::STATUS_WORKING;
> +        	case self::ACTION_REFUSE:
> +        		return $actualStatus = self::STATUS_REFUSAL;
> +        	case self::ACTION_FINISH:
> +        		return $actualStatus = self::STATUS_FINISH;
>
> Для чего $actualStatus = ? Это можно убрать, оставив просто возврат
> значения
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746283551>
> :
>
> > +        	case self::ACTION_RESPOND:
> +        		return $actualStatus = self::STATUS_WORKING;
> +        	case self::ACTION_REFUSE:
> +        		return $actualStatus = self::STATUS_REFUSAL;
> +        	case self::ACTION_FINISH:
> +        		return $actualStatus = self::STATUS_FINISH;
> +        }
> +        return null;
> +    }
> +
> +    /**
> +     * метод определяет карту допустимых действий для заказчика
> +     * @param string $status
> +     * @return $action;
> +     */
> +     public function getClientAllowedAction(string $status) :? string
>
> Статус не должен передаваться аргументом, он должен передаваться в
> конструктор
>
> «Определять список доступных действий в текущем статусе»
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746283730>
> :
>
> > +                 return $action = self::ACTION_CANCEL;
> +             case(self::STATUS_WORKING):
> +                 return $action = self::ACTION_FINISH;
>
> $action = можно убрать, оставив просто возврат значения
> ------------------------------
>
> In classes/TaskStatusAction.php
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#discussion_r746284413>
> :
>
> > +        return null;
> +    }
> +
> +    /**
> +     * метод определяет карту допустимых действий для заказчика
> +     * @param string $status
> +     * @return $action;
> +     */
> +     public function getClientAllowedAction(string $status) :? string
> +     {
> +         switch ($status) {
> +             case(self::STATUS_NEW):
> +                 return $action = self::ACTION_CANCEL;
> +             case(self::STATUS_WORKING):
> +                 return $action = self::ACTION_FINISH;
> +             case(self::STATUS_UNDO && self::STATUS_REFUSAL && self::STATUS_FINISH):
>
> Это так не работает. Если нужно сделать case из нескольких значений, то
> нужно перечислить несколько кейсов:
>
> switch ($status) {
> 	case 'test' [...]

2021-11-11 07:01 UTC, b1rdex requested changes

2021-11-11 07:01 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    //public string $action;
```suggestion
    private string $status;
```
Незачем делать статус публичным

2021-11-11 07:01 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public function getStatuses() :? array
```suggestion
    public function getStatuses(): array
```
тут не бывает null

2021-11-11 07:01 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public function getActiones() :? array
```suggestion
    public function getActiones(): array
```
тут не бывает null

2021-11-11 07:01 UTC, b1rdex commented on classes/TaskStatusAction.php
> +    public function getActualStatus(string $action) :? string
```suggestion
     */
    public function getActualStatus(string $action): ?string
```

2021-11-11 07:01 UTC, b1rdex commented on classes/TaskStatusAction.php
> +{
Нужно вернуть константы с ролями

2021-11-11 07:01 UTC, b1rdex commented on classes/TaskStatusAction.php
> +         return null;
```suggestion
     public function getAllowedAction(): array
     {
         switch ($this->status) {
             case(self::STATUS_NEW):
                 return [self::ACTION_CANCEL, self::ACTION_RESPOND];
             case(self::STATUS_WORKING):
                 return [self::ACTION_FINISH, self::ACTION_REFUSE];
             // это можно было не писать, т.к. в них ничего не делается и выполнение всё равно переходит к последнему return
             // case(self::STATUS_UNDO):
             // case(self::STATUS_REFUSAL):
             // case(self::STATUS_FINISH):
             //   break;
             }
         return [];
```
Не понял откуда синтаксис с `||`, он же сделает `return true` и это должно сломать тесты. Про массив я писал в прошлый раз

2021-11-11 07:01 UTC, b1rdex commented on testing/test_m1t2_allowedAction.php
> +assert($strategy->getAllowedAction(TaskStatusAction::STATUS_WORKING) == TaskStatusAction::ACTION_FINISH || TaskStatusAction::ACTION_REFUSE, 'Problem with allowed action for status WORKING');
Тут тоже странный синтаксис с `||`, нужно переделывать на массив

2021-11-12 10:03 UTC, b1rdex approved these changes

2021-11-12 10:03 UTC, merged

2021-11-12 10:20 UTC, nataliasevostyanova commented
Thanks!

пт, 12 нояб. 2021 г., 13:03 Anatoly Pashin ***@***.***>:

> Merged #2 <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2>
> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-yii/204543-task-force-2/pull/2#event-5608627829>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHXQGMZQTGJUJHJXYK6UMITULTRADANCNFSM5HPZDESA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>